### ISSUE TITLE
UnboundLocalError("local variable 'response' referenced before assignment",)

### ISSUE THREAD

**Issue by dcramer** [mattrobenolt/sentry-groveio#4]
Error processing 'post_process' on 'GroveIoMessage': UnboundLocalError("local variable 'response' referenced before assignment",)

Stacktrace (most recent call last):

  File "sentry/utils/safe.py", line 17, in safe_execute
    result = func(_args, *_kwargs)

  File "sentry_groveio/models.py", line 50, in post_process
    self.send_payload(token, service, event, group, message)

  File "sentry_groveio/models.py", line 77, in send_payload
    response.read()

**Comment by mattrobenolt** [comment]
Ha, that line isn't even needed. Removing now.

**Comment by mattrobenolt** [comment]
0.1.2 is pushed to PyPi.
